### ISSUE TITLE
Tutorial: toy reduction trees

### ISSUE THREAD

**Issue by anshumanmohan** [cucapra/calyx#1414]
Making progress systematically: 
1. Hand-write a sequential reduction tree.
2. Pipeline it in Calyx, by hand. Debug. Now you have a "golden output".
3. Try to get MrXL's `gen_calyx` to inch towards this.

Learn from the other frontends. They use the builder library (https://github.com/cucapra/calyx/pull/1229) in all components but the Control.

**Comment by susan-garry** [comment]
We're working on a very simple example: given an array of length 8, do up a reduce tree that sums its elements.
<img src=https://user-images.githubusercontent.com/24484834/234404627-b3806484-08b5-465c-9442-3d80895c9348.PNG width="400" />
​
The eight inputs get processed by a reduce tree of (4+2+1 =) 7 adders. Our hope is that all the adders in one level of the tree would run in parallel, meaning this would take 3 cycles in our case and  `tree_height` cycles generally. 
​
We're running into a silly bottleneck: reading the items from the array and putting them into the registers _itself_ takes one cycle per item, here 8 cycles. This dominates the time complexity in an unsatisfying way. 
​
A few options:
1. The above is fine.
2. We could do the read in _one_ cycle by running eight parallel reading routines. The issue is that each of the eight routines will require their own personal copy of the array.
3. We're missing something!

**Comment by rachitnigam** [comment]
Woo, Awesome to see progress on this! Couple of thoughts:
1. Y'all are learning the painful lesson of hardware design: you can make your compute as parallel as possible but if the memory doesn't support the throughput you want, you're stuck. You are absolutely right that if you do sequential reads from the memory, the reads are going to completely dominate the latency. The "right" solution is placing all the values in a register. 
2. The alternative solution is using "banked memories" (in the style Dahlia describes them). For example, let's say you have 32 elements that you want to sum up. One way to do that is create 8 memories with 4 elements each so that you can use your reduction tree at full utilization for 4 sums and then the final sum only utilizes half the reduction tree.
3. Pipelining! This is why pipelining is such a popular optimization. It allows you to "hide" the latency by interleaving the computation with memory access. In a world where you're truly stuck with a sequential memory, your best bet is you allocate exactly one adder that continuously sums up values as they show up from the memory. This way, you can achieve full utilization and the lowest possible latency.

**Comment by anshumanmohan** [comment]
Thank you Rachit! We spent a second working through this and we'd love to run our understanding past you so we can catch any confusion early. 

### Placing all the values in a register
Gotcha, though we're a little hesitant to ask that the values come pre-placed in registers. It feels like lifting the problem upstream and making it someone else's problem, and also it is not the interface that `map` currently exposes.

### Banking and Pipelining

Now I'll simplify your example a tad in order to work all the way through it. Here's the shared setup:

![IMG_0047](https://user-images.githubusercontent.com/10830208/234997724-0c059181-5f6c-434e-8a8d-cf41cb852095.PNG)

We have 16 elements and not 32, and we'll split them across four memories of size 4 each. I've named the variables `a` through `p` and ordered them somewhat suggestively in a column-major way. Critically, one _can_ read off an entire column in one beat of the clock.

The naïve idea to beat, described [above](https://github.com/cucapra/calyx/issues/1414#issuecomment-1522425517), takes:
Total hardware: one tree of height 4 (above we have a tree of height 3 but now we need height 4 in order to have 16 leaves)
Total time: 16 (for reads), plus 4 (the height of the tree) = 20

#### Banking sans pipelining

Stamp out four copies of the tree shown below. It has height 2 so that it can have 4 leaves. Below I show how to crunch through column 1 in three steps.

![IMG_0048](https://user-images.githubusercontent.com/10830208/234998358-6fa2133d-e7a3-4e9a-9a5f-ddc0a8e5e1b2.PNG)

Use the other trees to do the same for the other three columns. Then take the four column-answers and put them in the leaves of one of your trees. Three steps later, you have the sum of the column-answers, and you're done. 

This takes:
Total hardware: four trees of height 2
Total time: 3 + 3 = 6

#### Banking with pipelining

Now we'll introduce pipelining. We only need one tree of height 2. We'll also keep two registers on the side.

![IMG_0049](https://user-images.githubusercontent.com/10830208/234999806-75290cb7-3905-4a45-86df-2f0daecb263a.PNG)
![IMG_0050](https://user-images.githubusercontent.com/10830208/234999823-adb1eb5b-9acc-4507-8755-0d18e7fc6371.PNG)
![IMG_0051](https://user-images.githubusercontent.com/10830208/234999843-8a472900-6d8f-45ef-b183-85e0262a097e.PNG)

This takes:
Total hardware: one tree of height 2
Total time: 9

I've put a golden glow around steps 3 and 4 because they represent full utilization of the tree.

### Questions
1. First, and most important: does the above look right? Even small nitpicks are helpful so that we don't magnify our misunderstandings!
2. These trees are a bit of a fiction obviously; really there are just seven registers that are being orchestrated in a parent-child relationship. We were wondering if pipelining would require us to have extra registers to represent the internal nodes of the tree. Consider that, between steps 2 and 3, the root's left child node needed to transmit the answer `a+b` and also accept the inputs `e` and `f`. Is this truly one step for one register, or do we need to throw more time/hardware at this problem in order to get this right?
3. The `salmon+red` sorta sat around for three cycles before `blue+green` was ready. Are we missing something, or is this fine?

**Comment by rachitnigam** [comment]
Awesome, all of this looks great and I love the notes on this! Maybe y'all should do a 5 minute talk during the tutorial explaining the high-level ideas to people so they can try implementing this stuff.

Couple of notes:
1. I think almost everything looks right to me! The "striped banking" that you came up with is exactly how HLS tools bank memories (as well as Dahlia). It is important to bank things like that so that you can read adjacent values in parallel. Of course, this assume that you're performing some dense, spatially-local computation and it's an interesting question whether the programming model should support different kinds of access patterns (this is exactly what @andrewb1999's project is all about).
2. Ah, good question! This coordination of signal is what makes pipelining challenging. The way I read your diagrams is that there are no adders explicitly and you're just showing me the registers in which case between steps 2 & 3, the second layer is already performing the addition and getting ready to write the sum to the top layer while the bottom-most layer has also combinationally computed the sums and is getting ready to write values to the second layer.
3. That's right! There is a "sequential dependency" in your algorithm: That is the final set of inputs need to arrive at different points in time. If you truly want this to be the case, you'd probably want to delay the `salmon+red` till `blue+green` is available. A different solution is to treat the topmost register as an accumulator and simply accumulate values into it.

Hope this helps! Feel free to ask clarifying questions

**Comment by rachitnigam** [comment]
BTW, if its helpful, here is a Filament program to [generate reduction trees](https://github.com/cucapra/filament/blob/0677e40a3ebfc7f799ef7931316a5704bc89349d/tests/compile/reduction-tree.fil#L4)

**Comment by sampsyo** [comment]
Just wanted to say I think this is very much on the right track! A couple of things to remember:

1. Reduction tree width (at the bottom layer) = memory banking factor. So one parameter can control both.
2. Reduction trees are useful even without pipelining. So a "v1.0" of the optimization could do reduction trees that are not used in a pipelined way, and "v2.0" could pipeline them for additional parallelism.
