### ISSUE TITLE
Builder: infer more widths

### ISSUE THREAD

**Issue by anshumanmohan** [cucapra/calyx#1676]
The builder library can infer widths some of the time, but I think there are few low-hanging fruit that I'm missing.

### 1. `<cell>_use` helpers

Consider: 

https://github.com/cucapra/calyx/blob/630b3e39563491a9f72149f56cfbd140ec94ae9b/calyx-py/calyx/builder.py#L407-L409

I'd like to infer `width` from either `left` or `right` and free the user from having to specify it like:

https://github.com/cucapra/calyx/blob/630b3e39563491a9f72149f56cfbd140ec94ae9b/calyx-py/test/correctness/fifo.py#L39-L41

### 2. `reg` as a guide

Consider:

https://github.com/cucapra/calyx/blob/630b3e39563491a9f72149f56cfbd140ec94ae9b/calyx-py/calyx/builder.py#L454

I'd like to just get the `width` off of `reg`.

Just wanted to flag that it's a known thing, and that some simple attempts at fixing it have failed. Help or thoughts appreciated!

**Comment by sampsyo** [comment]
To summarize the current state of things, the `infer_width` function is designed to work for port expressions. In literal Calyx, this means it can infer the widths of stuff like `add.left`, `reg.out`, `this.inport`, and `gap[done]`.

For something like `incr`, width inference is already happening, of course, for stuff like this:
https://github.com/cucapra/calyx/blob/630b3e39563491a9f72149f56cfbd140ec94ae9b/calyx-py/calyx/builder.py#L467

The place where it doesn't work is this call to instantiate a `std_add` cell, because there is no port expression involved:
https://github.com/cucapra/calyx/blob/630b3e39563491a9f72149f56cfbd140ec94ae9b/calyx-py/calyx/builder.py#L463

The way to address this would be to factor out the little chunk of `infer_width` that gets the size of registers:
https://github.com/cucapra/calyx/blob/630b3e39563491a9f72149f56cfbd140ec94ae9b/calyx-py/calyx/builder.py#L1108-L1110

…and use that to parameterize the `std_add`.
