### ISSUE TITLE
Schedule Compaction Using Static Control 

### ISSUE THREAD

**Issue by paili0628** [cucapra/calyx#1717]
Suppose we have the following control program:
```
seq{A; B; C; D; }
```
 
`A` and `B` take 1 cycles. 
`C` and  `D` take 10 cycles. 

Also suppose the following requirements: 
`A` and `C` both must come before `B` 
`A` must come before `D`. 

We can schedule this using `static` control as follows: 
```
wires {
  static<11> group exec_seq {
   A[go] = %0 ? 1'd1;
   C[go] = %[0:9] ? 1'd1;
   D[go] = %[1:10] ? 1'd1;
   B[go] = %10 ? 1'd1;
  }
}

control {
 exec_seq;
}
```
Where we make the execution of the four programs as "tightly" scheduled as possible: each control program is executed immediately after all control programs it has data dependency on have finished executing.

To do this, we first come up with a data dependency graph for all the statements inside the `seq` control operator. For the program above, the graph looks like this: 
<img width="250" alt="Screen Shot 2023-09-06 at 6 00 43 PM" src="https://github.com/cucapra/calyx/assets/92661158/561246f4-b119-4ddb-95ed-0b48bdf2d259">

If the data dependency graph created has no cycles, then we can come up with a compact schedule with the following algorithm:

While the graph is non-empty{
 find a node with indegree 0;
 schedule the execution of the control program of the node at the cycle immediately after all control programs which the current control program has data dependency on have finished executing;
 remove the node along with all outgoing edges;
}

In the example above, we first schedule node A and C to be executed at cycle 0 (because they are not dependent on other control programs), then remove A and C (along with all edges on this graph). We then schedule D to be executed at cycle 1 (when A has finished executing) and B at cycle 10 (when both A and C have finished executing).

**Comment by calebmkim** [comment]
I think this all sounds good. I have a few thoughts. 

- How do we represent dependencies that are from combinational logic? For example, let's say we have groups `A` and `B` have no dependencies except that they use the same `std_add`? They obviously can't be run at the same time. We know either `A` has to be schedule before `B` or `B` has to be scheduled before `A`,  but we don't care which one. One option is to arbitrarily pick a dependency at random (maybe giving priority to the longer group or something?). This will lead to non-optimal solutions in some cases. Another option is to just aggresively duplicate combinational components, compactly schedule them, and then run cell sharing after we have compacted the schedule. 
- How helpful will this be in practice? i.e., how much will this improve performance of designs? I can look at the Polybench stuff that we have to get a sense. 
- (really small note): but for the example you gave, I think the assignment should be `C[go] = %[0:9] ? 1'd1;` since it needs to run 10 cycles. This obviously doesn't affect any of the points you made in this writeup though.
