### ISSUE TITLE
Generate `dat` files from FuTIL programs

### ISSUE THREAD

**Issue by sgpthomas** [cucapra/calyx#315]
It would be nice if something (probably fud? maybe the compiler) could look at a FuTIL program and generate a data json file with random data / zeroed out data. This would make it easier to go from writing a program -> testing it, makes it easier to give instructions to people about how to simulate FuTIL, etc.

**Comment by rachitnigam** [comment]
Its not going to be quite as easy since relevant type information is lost when generating FuTIL programs (signed vs unsigned vs fixed point).

**Comment by sampsyo** [comment]
This would indeed be super helpful… a few thoughts come to mind.

- We could ask the Dahlia compiler to generate this. Won't help with other frontends, obvi.
- The thing could just start by generating the structure with the names of memories, not the types. Could be better than nothing.
- It would certainly need help from the Calyx compiler, not just fud… because you need to parse the program at the very least, right? And you don't want to write a _second_ parser for the same language. :smiley:

It might also be worthwhile to think out of the box about other ways to make it easier to get from writing a Calyx program to running it, as @sgpthomas. Like better "linting" for JSON inputs, even if we don't actually generate them, for instance.

**Comment by rachitnigam** [comment]
We've started marking memories with the `@external(1)` annotation when we want to read/write values from them during simulation. This means that all this imaginary tool needs to do is walk over the memories and generate a JSON file based on the primitive they use. In the future, if the memories have more attributes that describe the shape of the data (bit/float/fixed-point) and its signedness, we can also use that to generate more relevant data.
