### ISSUE TITLE
Add error message in parser for malformed literals (eg: 0'd1)

### ISSUE THREAD

**Issue by EclecticGriffin** [cucapra/calyx#438]
Currently the parser will let you write literals like `0'd1` which don't make sense. These will hit an expected error path deeper in the compiler about the sizes not matching, but should probably be caught in the parser since literals of this sort are always wrong and likely the result of format confusion.

**Comment by sampsyo** [comment]
Yes, an error sounds good! For the reason that a zero-bit signal cannot represent the value 1. The same reason would apply for giving an error for `2'd42` because 42 is not representable in 2 bits.

(As an aside, we have previously discussed an occasional need for zero-bit signals… but even if we do that, you'd want a literal to be like `0'null` to represent a zero-value signal, not `0'd0` or whatever, which would be misleading.)
