### ISSUE TITLE
Constants not allowed in `invoke` arguments

### ISSUE THREAD

**Issue by sgpthomas** [cucapra/calyx#447]
This control statement:
```
invoke my_add(left = left_r.out, right = 32'd4)();
```
produces the following error message:
```
Error: Calyx Parser:   --> 56:48
   |
56 |       invoke my_add(left = left_r.out, right = 32'd4)();␊
   |                                                ^---
   |
   = expected port
```
We should allow constant literals in invoke arguments.

**Comment by rachitnigam** [comment]
There are two steps to this:
1. Updating the `futil_syntax.pest` (parser implementation) and the frontend AST representation.
2. The second is updating the functions that transform the input AST to the IR (ast_to_ir). This is not going to be easy. The reason I didn't do this in the first place is because it's kind of annoying to pass enough information to instantiate constants in the control program.

### Why is this hard?
The basic reason I didn't do this in the first place is because constants are magical in Calyx—they can "interned" when they are created and always refer to the same cell once they are instantiated.

If you write:
```
wires {
  x.in = 1'd1;
  y.in = 1'd1;
}
```

Both the `1'd1` refer to the same IR node. When the AST->IR transformer sees the first `1'd1`, it instantiates a new cell. However, for the second `1'd1`, it just returns the pointer to the previous node. This means that in the AST->IR functions, you need to pass in a mutable reference to the component which gets complicated.
