### ISSUE TITLE
Get unrolled Polybench benchmarks working with interpreter

### ISSUE THREAD

**Issue by rachitnigam** [cucapra/calyx#649]

**Comment by EclecticGriffin** [comment]
Seems likely that there's a bug in the state merging function for the stack environments, I'll update when I have a better sense of it's precise location & nature

**Comment by EclecticGriffin** [comment]
Okay I have determined the bug which is that `eval_empty` assumes that it's being run on a structural component (since that's sometimes what an empty group means) and it waits for the component to finish. This is obviously not the case when we're executing the empty branch of an if statement (the false branch) so it spins forever.

The solution is to fix the top-level check to see if the component is structural to appropriately dispatch `interp_cont` and `eval_empty` should just be a pass-through.

I should note that with this fix the unrolled benchmarks crash because multiple arms of a par write the same value to the same port
